[package]
name = "atomic-matrix"
version = "0.3.2"
edition = "2024"
authors = ['Dottsss']
description = "A lock-free, high end allocator primitive for high-performance IPC."
license = "Apache-2.0"
repository = "https://github.com/CodenamePhantom/AtomicMatrix"
keywords = ["allocator", "lock-free", "ipc", "shared-memory", "tlsf"]
categories = ["memory-management", "concurrency", "os"]
readme = "README.md"

[features]
default = []

[dependencies]
better_result = { path = "../better_result" }
memmap2 = "0.9.10"
libc = "0.2.186"
